import type { Metadata } from 'next'
import Header from '@/components/header'
import { FooterSection } from '@/components/footer2'

export const metadata: Metadata = {
    title: 'Tailark Quartz pages',
    description: 'Generated by create next app',
}

export default function MarketingLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            <Header />
            <main
                role="main"
                className="bg-background">
                {children}
            </main>
            <FooterSection />
        </>
    )
}